# Generated by Django 2.2 on 2019-04-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='story_points',
        ),
    ]
