# Generated by Django 2.2 on 2019-04-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_remove_card_story_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='business_value',
        ),
    ]
